### ISSUE TITLE
How to delete a session key?

### ISSUE THREAD

**Issue by bompus** [mcollina/fastify-secure-session#13]
Looking at the code, it doesn't seem possible to delete a key. All I can see is how to set it to null or empty string, which isn't great on my end for keeping a session cleaned up.

Would it be possible to add a .delete() or .remove() function, or possibly if you .set('myKey', null), it deletes the key from the session, but a dedicated function would probably be best to prevent any regression.

**Comment by mcollina** [comment]
would you like to send a PR?

Il giorno mer 13 feb 2019 alle 16:52 bompus <notifications@github.com> ha
scritto:

**Comment by bompus** [comment]
I knew you were going to say that :)

Which method do you prefer for deleting the cookie?

1. .set('myKey', undefined);
2. .set('myKey', ''); // matches browser spec closest
3. .delete('myKey'); // ensures no regression if somebody is currently setting to undefined/empty string

I can do whatever, just don't want to send over a PR that needs to be refactored to do something different than what you'd like.

**Comment by mcollina** [comment]
Why do you think setting it to an empty string matches the browser spec the
closest? I’m leaning towards delete(), as it would be similar to a Map.

Il giorno gio 14 feb 2019 alle 15:27 bompus <notifications@github.com> ha
scritto:

**Comment by bompus** [comment]
Actually, I may have already answered part of my original issue, which I didn't fully explain.

My original issue was this value:
var myVal = { a: 1, b: 2 };
.set('myKey', myVal);

In my case, I wanted to delete the 'b' key inside of myVal, which is an object. Easy, just set it undefined, no clue why I was trying empty string or null, when I already knew setting it undefined wouldn't stringify.

So to solve my original issue, that wasn't clarified enough:
var myVal = { a: 1, b: undefined }; // or delete myVal.b
.set('myKey', myVal);

Will keep things clean because it won't stringify 'b'.

But, technically, the question still remains as to whether there is any value in providing a mechanism to delete the session cookie entirely, so still let me know on that.

**Comment by bompus** [comment]
My fault again. This is why I shouldn't work this early in the morning. I thought that setting a cookie to an empty value in the browser would delete it, but in fact, you have to set a past-expires date on it.

With that, to completely delete the session cookie, I think .delete() makes the most sense, without needing to accept arguments.

Your thoughts?

> Why do you think setting it to an empty string matches the browser spec the closest? I’m leaning towards delete(), as it would be similar to a Map.

**Comment by mcollina** [comment]
+1 for delete

Il giorno gio 14 feb 2019 alle ore 15:45 bompus <notifications@github.com>
ha scritto:
