### ISSUE TITLE
How well does fastify-secure-session scale?

### ISSUE THREAD

**Issue by BLUEBOUNCE** [mcollina/fastify-secure-session#21]
From what I see it uses a memory store and since I'm pretty new to node (and js in general) I wonder how well this scales when having a lot of sessions. I'm just curious since fastify-session recommends to use a third party store (https://github.com/SerayaEryn/fastify-session/blob/master/README.md#store "Note: The default store should not be used in a production environment because it will leak memory.")

**Comment by mcollina** [comment]
These are different repos that implement different approach. This repo does not use any external storage, and store the session in a secure cookie. Open an issue in the other repo for question related to that.

**Comment by mcollina** [comment]
Also https://github.com/fastify/help for general fastify questions

**Comment by BLUEBOUNCE** [comment]
I honestly feel kinda stupid, but I understood how it works now.
