### ISSUE TITLE
route example

### ISSUE THREAD

**Issue by dsun9** [mcollina/fastify-secure-session#3]
Hi,

for some routes, I have small data session to save in cookie. sample code is as below. How do I modify this code to use fastify-secure-session?

const fastify = require('fastify')()

fastify.register(function (instance, options, next) {
  fastify.get('/foo', function (req, reply) {
    reply.send('no plugins affecting this route')
  })
  next()
})

fastify.register(function (instance, options, next) {
  instance
    .register(fastifyCookie)
    .register(require('fastify-static'))
    .register(require('fastify-multipart'))
    .register(require('fastify-formbody'))
    .get('/bar', function (req, reply) {
      reply.send('several plugins affect this route')
    })
  next()
})

**Comment by mcollina** [comment]
what is not clear in https://github.com/mcollina/fastify-secure-session/blob/master/example.js?

**Comment by dsun9** [comment]
./ will effect all routes? I don't want it for all routes. in the 2nd section, there are actually multiple routes, do I have to to register for each of them? any way to register once for /bar1, /bar2?
fastify.register(require('./'), {
  secret: 'averylogphrasebiggerthanthirtytwochars'
})

**Comment by mcollina** [comment]
I'm a bit lost on how you plan to use fastify. I would recommend to read the basics of node and the module system, and then go through the all the fastify docs, and all maybe some of https://nodeschool.io/ as well.

fastify.register(require('fastify-secure-session'), {
secret: 'CHANGE THIS'
})

if you place this on the root level, it will be available to every route.

**Comment by dsun9** [comment]
I managed to proceed, but the cookie setting below doesn't work, I want the Path to be '/', but it changes for different url

secret: 'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  cookie: {

	Path: '/'
	
  }

**Comment by mcollina** [comment]
Please upload a full example

**Comment by dsun9** [comment]
const fastify = require('fastify')();
const path = require('path')
const {upload,displayUpload} = require('./controllers/uploadController');
const {basicAuthentication,home} = require('./controllers/basicAuthenticationController');
const session = require('fastify-secure-session')

const sessionOptions = {
  secret: 'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  cookie: {
    secure: false,
	Path: '/',
	maxAge: 1000 * 60 * 60 * 24 * 7 * 26
  }
}
fastify.register(function (instance, options, next) {
  instance
    .register(session, sessionOptions)
    .register(require('fastify-static'), {root: path.join(__dirname, 'public')})
    .register(require('fastify-multipart'))
    .register(require('fastify-formbody'))
    .post("/auth/basic", basicAuthentication)
	.get("/home", home)
	.get("/displayUpload", displayUpload)
	.post("/upload", upload)
  next()
})

fastify.listen(process.env.PORT || 80, function (err) {
  if (err) throw err
})

**Comment by dsun9** [comment]
![image](https://user-images.githubusercontent.com/33603449/34222638-d5207a94-e581-11e7-97e9-6202bb89f71a.png)
